### PR TITLE
fix: add SKIP_COMMIT_FILES enviroment variable

### LINKED ISSUE #5819: [Feature][gitExtractor] Make commit files collection optional
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

One of the users from the community has large repos with over 20 million commit files to collect, which causes the following problem:

1. The time to collect Git data is too long
2. Errors occurred while writing data to the DevLake database

`
subtask collectGitCommits ended unexpectedly Wraps: (2) Error 1213: Deadlock found when trying to get lock; try restarting transaction Wraps: (3) Error 1213: Deadlock found when trying to get lock; try restarting transaction Error types: (1) *hintdetail.withDetail (2) *hintdetail.withDetail (3) *mysql.MySQLError
`

### Description

The ideal solution is to make `gitExtractor` incremental or all entities selectable, but it takes time. A quick fix is to provide a configuration to disable the collection of `commit_files`. This configuration can be data scope level, connection level, or global level.

### Related issues

_No response_

### Are you willing to submit a PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by abeizn**
### Summary
fix: add SKIP_COMMIT_FILES enviroment variable.

To bypass the commit file collector, you should set SKIP_COMMIT_FILES=true.

### Does this close any open issues?
Closes #5819 

### Screenshots
set SKIP_COMMIT_FILES enviroment variable, the devlake run results:
a1bb5665-9482-4f50-91f8-4e2cbbe88f1e

not set:
9d64cffd-fccd-4e09-b71d-ab758ced8883

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: backend/plugins/gitextractor/parser/repo.go [hunk 1]
```diff
@@ -331,9 +336,13 @@ func (r *GitRepo) getDiffComparedToParent(commitSha string, commit *git.Commit,
 	if err != nil {
 		return nil, errors.Convert(err)
 	}
-	err = r.storeCommitFilesFromDiff(commitSha, diff, componentMap)
-	if err != nil {
-		return nil, errors.Convert(err)
+	cfg := config.GetConfig()
+	skipCommitFiles := strings.TrimSpace(cfg.GetString(SkipCommitFiles))
```
Comment (klesh) [inline backend/plugins/gitextractor/parser/repo.go:340]: It would be easierTo use `GetBool`

**Review by klesh — APPROVED** [review]
