### PR TITLE
fix: azuredevops automigrate failed on newer gorm

### LINKED ISSUE #5687: [Bug][Core] Upgrade from DevLake v0.17 to v0.18 with Postgres results in panic error
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

After upgrading from DevLake v0.17 to v0.18, an error occurred. The error message was: "ALTER TABLE "_tool_azuredevops_gitpullrequests" ALTER COLUMN "connection_id" DROP NOT NULL panic: ERROR: column "connection_id" is in a primary key (SQLSTATE 42P16)".

### What do you expect to happen

The upgrade should have been completed successfully without any errors. The "connection_id" column should have been altered without causing a panic error.

### How to reproduce

Start with a DevLake v0.17 instance using Postgres as the database.
Upgrade the instance to DevLake v0.18.
Observe the error message.

### Anything else

5ed30455-5685-4ce7-84e5-34e916da9843

### Version

release-v0.18

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by klesh**
### Summary

dropping the "NOT NULL" constraint for Primary Key is not allowed in PG

### Does this close any open issues?
Closes #5687

### Screenshots
Snipaste_2023-07-19_17-05-26

### CODE REVIEW

File: backend/server/services/remote/plugin/plugin_impl.go [hunk 1]
```diff
@@ -57,6 +57,11 @@ type (
 	}
 )
 
+type NoPKModel struct {
```
Comment (CamilleTeruel) [inline backend/server/services/remote/plugin/plugin_impl.go:60]: Please rename to ToolModel and move to `remote/models/models.go`

**Review by CamilleTeruel — CHANGES_REQUESTED** [review]

File: backend/server/services/remote/plugin/plugin_impl.go (hunk 1 above)
Comment (klesh) [reply backend/server/services/remote/plugin/plugin_impl.go]: Done.

**Review by CamilleTeruel — APPROVED** [review]
