### PR TITLE
fix: jira/jenkins/github/tapd incremental collectors

### LINKED ISSUE #6075: [Bug][Framework] Some incremental collectors are not fully effective.
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

Some incremental collectors are not fully effective. 
collectorWithState.TimeAfter should be used here instead of data.TimeAfter
image

### What do you expect to happen

 incremental collectors are fully effective. 

### How to reproduce

run some plugins

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by abeizn**
### Summary
fix some plugins incremental collectors

### Does this close any open issues?
Closes #6075 

### Screenshots
jira:
first collect and the timeAfter="2023-03-12 16:00:00 +0000 UTC"
b169cd0e-d681-4299-8799-a99d23c55299

second collect:
09a74d25-fba8-41c3-87d1-f6088579300f

github:
first collect and the timeAfter="2023-09-12 16:00:00.000"
3544b954-465e-4687-a7f5-bbbf25cba3b7

second collect:
0688910c-1197-4bc7-b208-4c3cfdc1ee37

jenkins:
image
image

syncPolicy:
image

updated syncPolicy:
image

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: backend/plugins/github/tasks/comment_collector.go [hunk 1]
```diff
@@ -69,11 +68,11 @@ func CollectApiComments(taskCtx plugin.SubTaskContext) errors.Error {
 		Query: func(reqData *helper.RequestData) (url.Values, errors.Error) {
 			query := url.Values{}
 			query.Set("state", "all")
-			if syncPolicy != nil && syncPolicy.TimeAfter != nil {
+			if collectorWithState.TimeAfter != nil {
 				// Note that `since` is for filtering records by the `updated` time
 				// which is not ideal for semantic reasons and would result in slightly more records than expected.
 				// But we have no choice since it is the only available field we could exploit from the API.
```
Comment (klesh) [inline backend/plugins/github/tasks/comment_collector.go:74]: These 2 lines of comments should be deleted

File: backend/plugins/github/tasks/pr_review_comment_collector.go [hunk 2]
```diff
@@ -77,11 +76,11 @@ func CollectPrReviewComments(taskCtx plugin.SubTaskContext) errors.Error {
 		UrlTemplate: "repos/{{ .Params.Name }}/pulls/comments",
 		Query: func(reqData *helper.RequestData) (url.Values, errors.Error) {
 			query := url.Values{}
-			if syncPolicy != nil && syncPolicy.TimeAfter != nil {
+			if collectorWithState.TimeAfter != nil {
 				// Note that `since` is for filtering records by the `updated` time
 				// which is not ideal for semantic reasons and would result in slightly more records than expected.
 				// But we have no choice since it is the only available field we could exploit from the API.
```
Comment (klesh) [inline backend/plugins/github/tasks/pr_review_comment_collector.go:82]: delete

**Review by klesh — APPROVED** [review]
