### PR TITLE
fix(bamboo): fix status and result fields, add NOT_STARTED and BLOCKED status

### LINKED ISSUE #6107: [Bug][Bamboo] cicd_pipelines.result is missing a state
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

The result of Plan build, taken as _tool_bamboo_plan_builds build_state, will be standardized as'SUCCESS ',' FAILURE 'in the domain layer.
image

### What do you expect to happen

From the _tool_bamboo_deploy_build table, there is a NOT_BUILT status that needs to be added.
image

### How to reproduce

See above

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by d4x1**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [x] I have added relevant tests.
- [x] I have added relevant documentation.
- [x] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
What does this PR do?
1. Make up cicd_pipeline's status conversion function, add new status `NOT_STARTED` and `BLOCKED`.
2. Make result's default value its original state intead of an empty string.
3. Refact `GetResult` function, add `CaseInsensitive` option.

### Does this close any open issues?
Closes #6107 

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: backend/core/models/domainlayer/devops/cicd_pipeline.go [hunk 1]
```diff
@@ -51,50 +53,88 @@ const (
...
-	Manual  []string
-	Skipped []string
-	Default string
+	Success         []string
+	Failed          []string
+	Abort           []string
+	Manual          []string
+	Skipped         []string
+	Default         string
+	CaseInsensitive bool
```
Comment (abeizn) [inline backend/core/models/domainlayer/devops/cicd_pipeline.go:69]: Isn't the CaseInsensitive parameter necessary? Because you have set it to true (CaseInsensitive: true) by default in the converter, users cannot set it.

File: backend/plugins/bamboo/e2e/snapshot_tables/cicd_deployment_commits.csv [hunk 2]
```diff
@@ -1,8 +1,8 @@
-id,commit_sha,cicd_scope_id,cicd_deployment_id,name,result,status,environment,created_date,started_date,finished_date,duration_sec,ref_name,repo_id,repo_url,prev_success_deployment_commit_id
```
Comment (abeizn) [inline backend/plugins/bamboo/e2e/snapshot_tables/cicd_deployment_commits.csv:1]: Are these time parameters gone?

Comment (d4x1) [reply backend/plugins/bamboo/e2e/snapshot_tables/cicd_deployment_commits.csv:1]: > Are these time parameters gone?

@abeizn  wired, I just delete this csv and run the test. There are no deletions about  there parameters.

File: backend/core/models/domainlayer/devops/cicd_pipeline.go (hunk 1 above)
Comment (d4x1) [reply backend/core/models/domainlayer/devops/cicd_pipeline.go:69]: `CaseInsensitive`'s default value if false, which means "Abc" is different from "abc", that is the default behavior of current function.
Is `CaseInsensitive` is set to true, "Abc" and "abc" are the same.

Comment (d4x1) [reply backend/core/models/domainlayer/devops/cicd_pipeline.go]: Solved.

**Review by abeizn — APPROVED** [review]
lgtm
