### PR TITLE
fix: allow selecting FreeStyleProject in jenkins scopes UI

### LINKED ISSUE #7400: [Question][Jenkins] Most Jenkins Projects Not Selectable
## Question
I'm running version v1.0.0-beta5@e6ea5f6. Can you advise as to why almost all my Jenkins projects in the "Add Data Scope" section are not selectable.  I have tried with different Jenkins users (highest permission levels) and cannot determine why this is occurring.  I am running a self hosted Jenkins instance (version 2.363)

Thank you!

## Screenshots
image

### PR DESCRIPTION
**Pull request by gustavobini**
### Summary
Allows selecting Jenkins' FreeStyleProject in Jenkins scopes UI.

### Does this close any open issues?
Closes https://github.com/apache/incubator-devlake/issues/7400

### CODE REVIEW

**Review by klesh — APPROVED** [review]

File: backend/plugins/jenkins/api/remote_api.go [hunk 1]
```diff
@@ -55,17 +55,8 @@ func listJenkinsRemoteScopes(
 	getJobsPageCallBack := func(job *models.Job) errors.Error {
 		switch job.Class {
 		case "org.jenkinsci.plugins.workflow.job.WorkflowJob":
-			// this is a scope
```
Comment (abeizn) [inline backend/plugins/jenkins/api/remote_api.go:58]: Why delete this code? This resulted in many of my scopes not being displayed. @gustavobini  cc @klesh
