### PR TITLE
fix: no pipelines data when running pipelines on postgres

### LINKED ISSUE #5703: [Bug][Framework] no pipelines data when running pipelines on postgres
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

no pipelines data when running pipelines on postgres.
img_v2_f7770df0-40ac-4c46-9348-93800f6955dg
img_v2_ae03f0e7-953b-4d92-b2cd-1a01b255bccg

### What do you expect to happen

generate pipelines data on postgres

### How to reproduce

run a pipeline 

### Anything else

_No response_

### Version

v0.18.0-beta1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by abeizn**
### Summary
fix: no pipelines data when running pipelines
add
```
		if r != nil {
			msg = fmt.Sprintf("%v", r)
		}
```
to judge the normal situation

### Does this close any open issues?
Closes #5703 

### Screenshots
image

image

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: backend/helpers/dbhelper/txhelper.go [hunk 1]
```diff
@@ -70,17 +69,20 @@ func (l *TxHelper[E]) End() {
...
+		if r != nil {
+			msg = fmt.Sprintf("%v", r)
+		}
 	} else {
 		msg = err.Error()
 	}
+
 	if msg == "" {
 		errors.Must(l.tx.Commit())
 	}
```
Comment (klesh) [inline backend/helpers/dbhelper/txhelper.go:84]: else

**Review by klesh — APPROVED** [review]
LGTM
