### PR TITLE
Fix 6112

### LINKED ISSUE #6112: [Bug][Pagerduty] Unable to collect incidents with API token
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

401 error when collecting incidents from pagerduty with a valid token specified

### What do you expect to happen

Being able to collect incidents. 
Instead we have 401 returned by this call:
https://api.pagerduty.com/incidents?date_range=all&limit=100&offset=0&service_ids%5B%5D=PKRB4TU&sort_by=created_at%3Adesc&total=true

The issue is the fact that DevLake is not setting the Authentication header correctly: 
In the test endpoint (that works correctly) is being set with 
`"Authorization": fmt.Sprintf("Token token=%s", connection.Token)`
In the "PrepareTaskData" instead is set as follow:
`"Authorization": fmt.Sprintf("Token %s", connection.Token)` 

### How to reproduce

Try to collect incidents from a pagerduty cloud instance with a token

### Anything else

_No response_

### Version

v0.18.0

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by Marco-De-Stefani**
### Summary
Fixing #6112 and removing the typo in the version of golangci-lint 

### Does this close any open issues?
Closes #6112

### Screenshots
Before:
image
After:
image

### CODE REVIEW

**Comment by keon94** [comment]
Has PagerDuty made this change to their API recently? How come this wasn't an issue before?

**Comment by Marco-De-Stefani** [comment]
@keon94 I think that Pagerduty API has not been changed, by having a quick look at the GH history I believe this has been introduced with the refactor of the Pagerduty plugin.
It looks to me that the first version of the plugin implemented in the revision eef06e96e95ad9e95fd9bc4dde27cc55123e0740 uses the correct token.
In that revision, the connection.go file contains --> 
Token string `mapstructure:"token" env:"PAGERDUTY_AUTH" validate:"required" encrypt:"yes"`

**Comment by keon94** [comment]
@Marco-De-Stefani very odd. I tried running the pagerduty tests under `test/e2e/manual/pagerduty` with and without this change and it works for me, so I don't know what's going on. Either way, there's a better fix for this which I've pointed out in the file changes.

File: backend/plugins/pagerduty/impl/impl.go [hunk 1]
```diff
@@ -109,7 +109,7 @@ func (p PagerDuty) PrepareTaskData(taskCtx plugin.TaskContext, options map[strin
 	}
 
 	client, err := helper.NewApiClient(taskCtx.GetContext(), connection.Endpoint, map[string]string{
```
Comment (keon94) [inline backend/plugins/pagerduty/impl/impl.go:111]: replace all of this with:
```go
client, err := helper.NewApiClientFromConnection(taskCtx.GetContext(), taskCtx, connection)
```

Comment (keon94) [reply backend/plugins/pagerduty/impl/impl.go:111]: This will utilize this [code](https://github.com/apache/incubator-devlake/blob/8bcacd8eeefe4c88d0a0e5135bd026feac94a5b3/backend/plugins/pagerduty/models/connection.go#L33) which already correctly sets the token.

**Comment by Marco-De-Stefani** [comment]
> @Marco-De-Stefani very odd. I tried running the pagerduty tests under `test/e2e/manual/pagerduty` with and without this change and it works for me, so I don't know what's going on. Either way, there's a better fix for this which I've pointed out in the file changes.

I noticed that as well, it works cause at line 125 of the pagerduty_test.go file it's calling "PagerDutyAccessToken" which sets the token in the correct way :)

**Comment by Marco-De-Stefani** [comment]
> > > @Marco-De-Stefani very odd. I tried running the pagerduty tests under `test/e2e/manual/pagerduty` with and without this change and it works for me, so I don't know what's going on. Either way, there's a better fix for this which I've pointed out in the file changes.
> > 
> > 
> > I noticed that as well, it works cause at line 125 of the pagerduty_test.go file it's calling "PagerDutyAccessToken" which sets the token in the correct way :)
> 
> That token object doesn't have an influence [here](https://github.com/apache/incubator-devlake/blob/73883730362d16148cee167cb0cd5f13edc28f62/backend/plugins/pagerduty/impl/impl.go#L111) though. The test still passes without "token=". Here's what my debugger captures - connection.Token is just the raw token. image

Weird, I'll try to debug that as well

**Review by keon94 — APPROVED** [review]
LGTM

**Comment by klesh** [comment]
Hi, Nice work, thanks for your contribution, would you like to cherry-pick it back to [release v0.19](https://github.com/apache/incubator-devlake/tree/release-v0.19)?
