### PR TITLE
Fix zentao plugin's type mappings

### LINKED ISSUE #5755: [Bug][Zentao] Adjust the issue type/status mapping configuration
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

- The type mapping for `story` is still using 'Type' + 'Category'
- The status mapping for `story` is still using 'Status' + 'Stage'
image

The configuration for Zentao `bugs` and `tasks` are also using the combination of two fields.

### What do you expect to happen

Zentao stories, bugs and tasks should ALL 
- use `original_type` for type mapping 
- use `original_status` for status mapping 

### How to reproduce

-

### Anything else

_No response_

### Version

v0.18.0-beta3

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by d4x1**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [x] I have added relevant tests.
- [x] I have added relevant documentation.
- [x] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
What does this PR do?
update zentao plugin,  do type mappings in domain layer instead of tool layer.

### Does this close any open issues?
Closes #5755 

### Screenshots
Include any relevant screenshots here.
image

image

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: backend/helpers/dbhelper/txhelper.go [hunk 1]
```diff
@@ -44,7 +44,7 @@ func (l *TxHelper[E]) Begin() dal.Transaction {
 
 // LockTablesTimeout locks tables with timeout
 func (l *TxHelper[E]) LockTablesTimeout(timeout time.Duration, lockTables dal.LockTables) errors.Error {
-	println("timeout", timeout)
```
Comment (klesh) [inline backend/helpers/dbhelper/txhelper.go:47]: Please remove all these debugging lines using `println` and `fmt.Println`, or use `logger` instead

**Review by klesh — APPROVED** [review]
