### PR TITLE
fix(jira): fix type for Jira issue descriptions

### LINKED ISSUE #8558: [Bug][Jira] Unmarshal error for epic description with rich text
### Bug Description

The Jira plugin fails to collect epics when the `description` field contains rich text (Atlassian Document Format) instead of a plain string. This leads to a JSON unmarshaling error during data collection, causing the pipeline to fail.

### Root Cause

The Go struct `apiv2models.Issue` in `backend/plugins/jira/tasks/apiv2models/issue.go` defines the `Description` field as a `string`. However, the Jira API returns a complex JSON object for rich text fields, causing a type mismatch during JSON unmarshaling.

### Stack Trace
```
attached stack trace -- stack trace: | github.com/apache/incubator-devlake/server/services.runPipeline | /app/server/services/pipeline_runner.go:79 | [...repeated from below...] Wraps: (2) Error running pipeline 3. Wraps: (3) attached stack trace -- stack trace: | github.com/apache/incubator-devlake/server/services.RunTasksStandalone | /app/server/services/task.go:217 | github.com/apache/incubator-devlake/server/services.(*pipelineRunner).runPipelineStandalone.func1 | /app/server/services/pipeline_runner.go:42 | github.com/apache/incubator-devlake/core/runner.runPipelineTasks | /app/core/runner/run_pipeline.go:90 | github.com/apache/incubator-devlake/core/runner.RunPipeline | /app/core/runner/run_pipeline.go:54 | github.com/apache/incubator-devlake/server/services.(*pipelineRunner).runPipelineStandalone | /app/server/services/pipeline_runner.go:38 | github.com/apache/incubator-devlake/server/services.runPipeline | /app/server/services/pipeline_runner.go:76 | github.com/apache/incubator-devlake/server/services.RunPipelineInQueue.func1 | /app/server/services/pipeline.go:358 | runtime.goexit | /usr/local/go/src/runtime/asm_arm64.s:1172 Wraps: (4) attached stack trace | -- stack trace: | | github.com/apache/incubator-devlake/server/services.RunTasksStandalone.func1 | | /app/server/services/task.go:189 | Wraps: (2) Error running task 15. | Wraps: (3) attached stack trace | -- stack trace: | | github.com/apache/incubator-devlake/core/runner.RunPluginSubTasks | | /app/core/runner/run_task.go:333 | | [...repeated from below...] | Wraps: (4) subtask extractEpics ended unexpectedly | Wraps: (5) attached stack trace | -- stack trace: | | github.com/apache/incubator-devlake/helpers/pluginhelper/api.(*StatefulApiExtractor[...]).Execute | | /app/helpers/pluginhelper/api/api_extractor_stateful.go:159 | | github.com/apache/incubator-devlake/plugins/jira/tasks.ExtractEpics | | /app/plugins/jira/tasks/epic_extractor.go:96 | | github.com/apache/incubator-devlake/core/runner.runSubtask | | /app/core/runner/run_task.go:425 | | github.com/apache/incubator-devlake/core/runner.RunPluginSubTasks | | /app/core/runner/run_task.go:330 | | github.com/apache/incubator-devlake/core/runner.RunPluginTask | | /app/core/runner/run_task.go:165 | | github.com/apache/incubator-devlake/core/runner.RunTask | | /app/core/runner/run_task.go:139 | | github.com/apache/incubator-devlake/server/services.runTaskStandalone | | /app/server/services/task_runner.go:114 | | github.com/apache/incubator-devlake/server/services.RunTasksStandalone.func1 | | /app/server/services/task.go:187 | | runtime.goexit | | /usr/local/go/src/runtime/asm_arm64.s:1172 | Wraps: (6) json: cannot unmarshal object into Go struct field .fields.description of type string | Wraps: (7) json: cannot unmarshal object into Go struct field .fields.description of type string | Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.withPrefix (5) *withstack.withStack (6) *errutil.withPrefix (7) *json.UnmarshalTypeError Error types: (1) *withstack.withStack (2) *errutil.withPrefix (3) *withstack.withStack (4) *errutil.leafError
```

Version
v1.0.3-beta4

Are you willing to submit PR?
- [ ] Yes I am willing to submit a PR!

Code of Conduct:
- [x] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by GoSimplicity**
This fix #8558  ensures that the Jira plugin no longer throws JSON deserialization errors when encountering rich-text descriptions, allowing the pipeline to continue running smoothly. Existing string-only descriptions remain fully supported, guaranteeing backward compatibility.

### CODE REVIEW

**Comment by davinogueiradev** [comment]
I'm testing locally, and not work for all scenarios, reading the [documentation](https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/#version) others field can be text rich.

```
Issue.Description 
Comment.Body
Worklog.Comment
```

**Comment by GoSimplicity** [comment]
> I'm testing locally, and not work for all scenarios, reading the [documentation](https://developer.atlassian.com/cloud/jira/platform/rest/v3/intro/#version) others field can be text rich.
> 
> ```
> Issue.Description 
> Comment.Body
> Worklog.Comment
> ```

Thanks for the review! This fix covers all rich text fields (Issue.Description, Comment.Body, Worklog.Comment) that can cause the ADF unmarshaling error, including Epic descriptions since they use the Issue struct. The FlexibleDescription type handles both string and ADF formats with full backward compatibility. If you encounter specific scenarios that don't work, please share the error details.

**Review by davinogueiradev — APPROVED** [review]
LGTM.
I did some tests and passed them all

File: backend/plugins/jira/tasks/apiv2models/issue.go [hunk 1]
```diff
@@ -19,13 +19,141 @@ package apiv2models
...
 	"encoding/json"
+	"strings"
 	"time"
 
 	"github.com/apache/incubator-devlake/core/errors"
 	"github.com/apache/incubator-devlake/core/models/common"
 	"github.com/apache/incubator-devlake/plugins/jira/models"
 )
 
+// FlexibleDescription supports both plain text and ADF (Atlassian Document Format) for Jira description field
```
Comment (klesh) [inline backend/plugins/jira/tasks/apiv2models/issue.go:30]: Could you add a link to the Atlassian Document Format (e.g., an example) for reference, so others can easily update the logic in the future? Thanks in advance.

Comment (GoSimplicity) [reply backend/plugins/jira/tasks/apiv2models/issue.go:30]: Of course, I will add it later.

**Review by klesh — APPROVED** [review]
LGTM
