### PR TITLE
Exclude Draft Releases in ReleaseExtractor

### LINKED ISSUE #8148: [Bug][Github] Extractor failing with draft release
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When running the pipeline against a github repo that contains a draft release it fails due to not having a incorrect datetime value for the published at column

image

### What do you expect to happen

I would expect this to ignore the draft release.

### How to reproduce

Create a draft PR in a repository, run the Collect Data and see the error on the github_graphql stage.

### Anything else

We have this occur across a number of our projects where we use a GitHub Action to automatically draft a new PR for the next release.

### Version

v1.0.1

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by J0shSkqlq**
### Summary
Exclude Draft Releases in ReleaseExtractor to avoid bug due to malformed PublishedAt field.

### Does this close any open issues?
Closes #8148

### CODE REVIEW

**Review by klesh — DISMISSED** [review]
LGTM

File: backend/plugins/github_graphql/tasks/release_extractor.go [hunk 1]
```diff
@@ -55,7 +55,9 @@ func ExtractReleases(taskCtx plugin.SubTaskContext) errors.Error {
 			if err != nil {
 				return nil, err
 			}
-
+			if release.IsDraft {
+				return nil, nil
```
Comment (klesh) [inline backend/plugins/github_graphql/tasks/release_extractor.go:59]: golang lint failed, I think it was caused by the trailing spaces, can you remove them?

Comment (J0shSkqlq) [reply backend/plugins/github_graphql/tasks/release_extractor.go]: Fixed it, but had to force push since the commit message lint failed as well.

**Review by klesh — APPROVED** [review]
LGTM

**Comment by klesh** [comment]
Thanks for your contribution, would you like to create another PR to the release-v1.0 branch  so it can be released faster.

**Comment by Startrekzky** [comment]
LGTM
