### PR TITLE
fix: fix test connection timeout and remote api error

### LINKED ISSUE #5804: [Bug][Zentao] Database Connection Timeout Causes ZenTao TestConnection api Timeout in DevLake
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When calling the ZenTao connection information verification api (test connection) in DevLake, if the database connection times out, the interface also times out.

### What do you expect to happen

Instead of timing out, the ZenTao api should return an error message indicating that the database connection validation failed (dbUrl invalid). This behavior would be consistent with the error message returned when database authorization fails.

### How to reproduce

1. Set up DevLake to interact with ZenTao.
2. Initiate a call to the ZenTao connection information verification api. (with a dbUrl that is not running a mysql)
3. Observe that the ZenTao interface also times out.

### Anything else

_No response_

### Version

release-v0.18

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by mindlesscloud**
### Summary
- support set timeout on testing db connection 
- fix the remote API JSON parsing error by removing the field `TotalReal` from the model `ZentaoProject`

### Does this close any open issues?
Closes #5804 

### Screenshots
image

### CODE REVIEW

File: backend/plugins/zentao/models/project.go [hunk 1]
```diff
@@ -93,8 +93,8 @@ type ZentaoProject struct {
 	TotalConsumed float64 `json:"totalConsumed" mapstructure:"totalConsumed"`
 	TotalLeft     float64 `json:"totalLeft" mapstructure:"totalLeft"`
 	Progress      float64 `json:"progress" mapstructure:"progress"`
-	TotalReal     int     `json:"totalReal" mapstructure:"totalReal"`
-	ScopeConfigId uint64  `json:"scopeConfigId,omitempty" mapstructure:"scopeConfigId"`
+	//TotalReal     int     `json:"totalReal" mapstructure:"totalReal"`
```
Comment (abeizn) [inline backend/plugins/zentao/models/project.go:96]: please delete it

**Review by abeizn — APPROVED** [review]
lgtm
