### PR TITLE
fix: issue relationships struct

### LINKED ISSUE #5688: [Feature][Data Model] Modeling issue relations
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

As a product manager, I want to measure 
- the number of bugs associated with a feature, or 
- the total development time of subtasks under a story, or 
- the duration of tasks associated with a story. Therefore, DevLake is required to store the relationship between issues.

However, DevLake v0.18 does not have an entity that stores the relationship between issues except for a `parent_issue_id` field in the issues table.

### Solution

Provide table(s) to model the relationship between issues. The table(s) are designed for measuring metrics by SQL like:
```
-- Assume that table issue_relations has 3 fields issue_1, original_relation, relation, issue_2
-- The following SQL is what DevLake users would be writing

select i1.id, i1.title, sum(i2.time_spent_minutes), sum(i2.eloc) 
from issues i1
    join issue_relations ir on i1.id = ir.issue_1_id
    join issues i2 on ir.issue_2_id = i2.id
where 
    -- Users have to customize the values of `type` and `relation`
    i1.type = 'user-story'
    and ir.relation = 'related-to'
group by 1,2
```

### Action Items

- [x] design: Design table(s) to store the relationship between issues, the index of the table(s) should consider the SQL above. The minimal required attributes are:
   - issue_id
   - relation
   - target_issue_id
   - original_relation
- [x] coding: Collect the issue relationship data in Jira plugin in v0.19. (TAPD, Zentao for later)
- [x] docs: Add the table description to the [domain layer doc](https://devlake.apache.org/docs/DataModels/DevLakeDomainLayerSchema#domain-1---issue-tracking)

### Related issues

related to #5747 

### Are you willing to submit a PR?

- [x] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by abeizn**
### Summary
Modify the issue relationships structure to ensure that it can be associated with the 'issues' table.

### Does this close any open issues?
Closes #5688 

### Screenshots
image

image

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: backend/core/models/migrationscripts/archived/issue_relationship.go [hunk 1]
```diff
@@ -18,11 +18,10 @@ limitations under the License.
...
 
 type IssueRelationship struct {
-	DomainEntity
-
-	SourceIssueId uint64 `gorm:"index"`
-	TargetIssueId uint64
+	SourceIssueId string `gorm:"primaryKey;type:varchar(255);index"`
+	TargetIssueId string `gorm:"primaryKey;type:varchar(255)"`
 	OriginalType  string `gorm:"type:varchar(255)"`
+	NoPKModel
```
Comment (klesh) [inline backend/core/models/migrationscripts/archived/issue_relationship.go:24]: should be a of the pk

Comment (abeizn) [reply backend/core/models/migrationscripts/archived/issue_relationship.go:24]: I think this may not be a of the pk

Comment (abeizn) [reply backend/core/models/migrationscripts/archived/issue_relationship.go:24]: done

**Review by klesh — APPROVED** [review]
