### PR TITLE
Feat support api key, update nginx conf, fix some bugs

### LINKED ISSUE #5791: [Feature][API key management] Support api keys settings
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar feature requirement.

### Use case

There are serveral scenarios that need api keys.
1. With webhook connections,  user can post data via devlake's apis, there are no mechanism to protect there apis are only used by internal caller, and prevent them from attack.
2. There are many configurations in devlake, some can be set in its front web page, however not all operations must be completed on the web page, sometime an open api is enough. Open API mechanism is wanted, and we need api keys to protect our open api.

### Description

1. When a webhook connection is created or deleted, an api key is generated/deleted and configured with the current webhook automatically. And a button called "Revoke and Regenerate API Key" is needed too.
2. In devlake's config ui, add "API Keys Management". User can do basic CURD operations for api keys.  I think these points should be noted:
    - api keys used by webhook shouldn't be list in the API Keys Management
    - api keys should have their `expiration time`, it's an optional field
    - all api keys are encypted, the raw api key literals can be seen only the first time it was created
 

### Related issues

None.

### Are you willing to submit a PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by d4x1**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [x] I have added relevant tests.
- [x] I have added relevant documentation.
- [x] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
1. remove basic auth for path `/api/rest` in nginx conf.
2. fix webhook's apis
3. fix some other bugs

### Does this close any open issues?
Closes #5791

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: backend/server/api/middlewares.go [hunk 1]
```diff
@@ -105,14 +105,15 @@ func RestAuthentication(router *gin.Engine, basicRes context.BasicRes) gin.Handl
 	}
 	apiKeyHelper := apikeyhelper.NewApiKeyHelper(basicRes, logger)
 	return func(c *gin.Context) {
-		path := c.Request.URL.Path
-		path = strings.TrimPrefix(path, "/api")
+		rawPath := c.Request.URL.Path
+		path := strings.TrimPrefix(rawPath, "/api")
```
Comment (klesh) [inline backend/server/api/middlewares.go:109]: This is not necessary because `nginx` already did it.

Comment (d4x1) [reply backend/server/api/middlewares.go:109]: Got it.

**Review by klesh — APPROVED** [review]
