### PR TITLE
Change the type of `duration_sec` from int to float

### LINKED ISSUE #6136: [Bug][CICD] Change the type of `duration_sec` from int to float
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

A community user reported that many of his Jenkins builds' duration were between 0 - 1s, e.g. 325ms. However, the `duration_sec` for these builds is all set to 0.

### What do you expect to happen

The type of `duration_sec` is better to use float, not int. The logic should apply to all duration-type fields:

- [ ] cicd_pipelines.duration_sec
- [ ] cicd_tasks.duration_sec
- [ ] cicd_deployment_commits.duration_sec
- [ ] cicd_deployments.duration_sec

### How to reproduce
N/A

### Anything else

_No response_

### Version

main

### Are you willing to submit PR?

- [ ] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by d4x1**
### ⚠️ Pre Checklist

> Please complete _ALL_ items in this checklist, and remove before submitting

- [x] I have read through the [Contributing Documentation](https://devlake.apache.org/community/).
- [x] I have added relevant tests.
- [x] I have added relevant documentation.
- [x] I will add labels to the PR, such as `pr-type/bug-fix`, `pr-type/feature-development`, etc.

### Summary
What does this PR do?
Fix #6136 

### Does this close any open issues?
Closes #6136 

### Screenshots
Include any relevant screenshots here.
image
image
image
image

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: backend/plugins/jenkins/tasks/stage_convertor.go [hunk 1]
```diff
@@ -99,14 +99,13 @@ func ConvertStages(taskCtx plugin.SubTaskContext) (err errors.Error) {
 			if body.Name == "" {
 				return nil, err
 			}
-			var durationMillis int
+			var durationMillis int64
```
Comment (abeizn) [inline backend/plugins/jenkins/tasks/stage_convertor.go:102]: float?

Comment (d4x1) [reply backend/plugins/jenkins/tasks/stage_convertor.go:102]: @abeizn  it's used in  https://github.com/apache/incubator-devlake/pull/6465/files/f5c07a15ba95e0bed72b4e38978541c806bb269b#diff-04993880854c505f74bc13205726cd68e47ed4a05ba170cdf2ca864abef43d4cL125 , I think keeping it `int64` is proper.

**Review by abeizn — APPROVED** [review]
