### PR TITLE
[fix-5697][Pydevlake]: Fix AddColumn op possibly deleting a column

### LINKED ISSUE #5697: [Bug][Azure DevOps] Entities Column Missing
### Search before asking

- [X] I had searched in the [issues](https://github.com/apache/incubator-devlake/issues?q=is%3Aissue) and found no similar issues.

### What happened

When standing up a new v0.18.0-beta1 deployment and trying to create scope config, it errors indicating that the entities column does not exist on the _tool_azuredevops_gitrepositoryconfigs table.

```
time="2023-07-18 16:55:18" level=info msg="/app/impls/dalgorm/dalgorm.go:196 Error 1054 (42S22): Unknown column 'entities' in 'field list'
[1.704ms] [rows:0] INSERT INTO `_tool_azuredevops_gitrepositoryconfigs` (`created_at`,`updated_at`,`entities`,`connection_id`,`name`,`refdiff`,`deployment_pattern`,`production_pattern`) VALUES ('2023-07-18 16:55:18.926','2023-07-18 16:55:18.926','["CODE","CODEREVIEW","CROSS","CICD"]',1,'DevSecOps Scope Config',NULL,'(deploy|push-image)','')"
```

### What do you expect to happen

The column to exist. 

### How to reproduce

Stand up a new v0.18.0-beta1 environment. The 

### Anything else

_No response_

### Version

v0.18.0-beta1

### Are you willing to submit PR?

- [X] Yes I am willing to submit a PR!

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://www.apache.org/foundation/policies/conduct)

### PR DESCRIPTION
**Pull request by keon94**
### Summary
What does this PR do?

### Does this close any open issues?
Closes #5697 

### Screenshots
Include any relevant screenshots here.

### Other Information
Any other information that is important to this PR.

### CODE REVIEW

File: backend/server/services/remote/plugin/plugin_impl.go [hunk 1]
```diff
@@ -231,28 +231,35 @@ func (p *remotePluginImpl) ApiResources() map[string]map[string]plugin.ApiResour
...
-		err = api.CallDB(db.AutoMigrate, toolModelTabler.New())
+		err = p.createTable(toolModelTabler.New())
 		if err != nil {
 			return err
 		}
 	}
 	return nil
 }
 
+func (p *remotePluginImpl) createTable(tbl coreModels.DynamicTabler) errors.Error {
```
Comment (CamilleTeruel) [inline backend/server/services/remote/plugin/plugin_impl.go:255]: This change disables all automigrations but table creation, and I thought we settled on adding a CreateTable op instead?

Comment (keon94) [reply backend/server/services/remote/plugin/plugin_impl.go:255]: Not in this ticket. I'll handle that in #5689. For now, we create tables like this, and every other migration is done manually

**Comment by keon94** [comment]
> @keon94 how about the corrupted schema? will it be fixed automatically after upgrade ?

I pushed a commit to re-trigger that migration. It'll work whether that column is present or not.

**Review by klesh — APPROVED** [review]
